spring:
  profiles:
    active: h2
  #设置spring-boot 编码格式
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
#设置tomcat参数
server:
  port: 8181
  servlet:
    context-path: /yang
  #设置spring-boot 编码格式
  tomcat:
    uri-encoding: UTF-8
#设置spring-boot 编码格式
banner:
  charset: UTF-8


#mybatis:
#  #mapper映射文件路径
##  mapper-locations: com.ityang.basic.mapper.*
#  #别名实体类注解路径
##  type-aliases-package: com.ityang.entity
#  #配置
#  configuration:
#    #是否自动命名驼峰转换
#    mapUnderscoreToCamelCase: true
#    #定义全局变量
#    variables:
#      dbType: oracle
yang:
  dbType: oracle